fix "pass_all_args" for roslaunch-check
ros/ros_comm pull request #1368
Opened 2018-04-17 12:52 UTC by jabbenseth

the option "pass_all_args" was not recognized by roslaunch checks. This works as expected on "our" launch files which create a mixed tree using the "pass_all_args" option as well as explicit argument forwarding

2018-04-24 14:13 UTC, mikepurvis commented
Thanks for this contribution. As the active branch has changed, please retarget this to `melodic-devel`, and it will be considered after merge for backport to Kinetic and Lunar.

Please also add a test-case which exposes the problem and is fixed by your proposed change. I would suggest doing so in this file:

https://github.com/ros/ros_comm/blob/melodic-devel/tools/roslaunch/resources/example.launch

There are [several tests](https://github.com/ros/ros_comm/search?q=%22example.launch%22) which load and process this launch file in different contexts; it shouldn't be hard to make one of them fail.

2018-04-25 14:10 UTC, ipa-jba commented
I added a test which exposed the mentioned problem. However if i ran the test manually (`rosrun test_roslaunch test_roslaunch_check.py`) it worked but with `rostest test_roslaunch roslaunch.test` I ran into troubles:
```
'unused args [__name, __log] for include of [/…/src/ros_comm/tools/roslaunch/resources/example-args.launch]' is not None
```
Somehow the implicitly defined arguments "__name" and "__log" for the node specified in the testfile get forwarded and end up in the test environment as well. They are blacklisted in https://github.com/ros/ros_comm/pull/1368/commits/7fb090fa3d2f2cce8fb04553b58401293a902667

Finally my original fix is applied in https://github.com/ros/ros_comm/pull/1368/commits/c8ed560b34e3257ddccf8a14bd7b3e8d46c6d3ee

2018-04-25 19:22 UTC, mikepurvis requested changes

2018-04-25 19:22 UTC, mikepurvis commented on test/test_roslaunch/test/test_roslaunch_check.py
> +    rostest.run(PKG, NAME, TestRoslaunchCheck, sys.argv)
You can filter `argv` using a rospy helper, see: http://wiki.ros.org/rospy/Overview/Initialization%20and%20Shutdown#Accessing_your_command-line_arguments

However, I don't think that's quite the right approach here— AFAICT this doesn't need to be a rostest at all. Rostests are specifically tests which take place in the full roslaunch environment (where a rosmaster and param server are present). What you have here could just be a regular nosetest. See `catkin_add_nosetests` documentation and some examples:

http://docs.ros.org/melodic/api/catkin/html/howto/format2/python_nose_configuration.html
https://github.com/ros/ros_comm/search?q=catkin_add_nosetests

This should allow you to drop the hack in `xmlloader.py` as well.

2018-04-26 18:52 UTC, mikepurvis approved these changes

2018-04-26 18:58 UTC, mikepurvis commented
Looks great, thanks for your patience in iterating on this with me.

2018-04-26 18:58 UTC, merged