remove messages that are newer than the newly added message
ros/ros_comm pull request #1438
Opened 2018-06-19 15:25 UTC by christian-rauch

In some circumstances, when replaying a log in loop mode (-l) the synchronisation blocks because messages jump back in time when restarting the log. This commit removes messages that are newer than the newly added message, enabling to synchronise looped log files. This could optionally enabled via a parameter that gives the maximum tolerated backward jump in time.

2018-06-19 20:20 UTC, tfoote requested changes
Logic to clear the filter when looping bag playback might make sense but I don't think that this is the right approach. It assumes all messages arrive in order except for a loop which is not guarenteed. There could easily be multiple publishers and publishers with higher latency.

There is logic in tf2_ros to reset it's buffers if the clock jumps backwards. I would suggest looking at that sort of logic as that is much more clearly a time discontinuity and behavior should change. Rather than possibly a delayed message arriving into a synchronizer.

2018-06-20 10:55 UTC, christian-rauch commented
I agree that `/clock` is a more sensible reference for the time than the timestamped messages. I implemented the buffer clearing logic like in https://github.com/ros/geometry2/pull/68 (I think this is the logic you were referring to).

2018-06-20 19:09 UTC, tfoote commented
That looks better to me. Two comments though.

With the additional use of `now()` the [mock initialization](https://github.com/ros/ros_comm/blob/melodic-devel/utilities/message_filters/test/test_approxsync.py#L101) of the time in the test needs to be moved earlier.

And the logic should provide a warning about the reset. Otherwise this could be triggered regularly and all data would potentially be silently dropped.

2018-06-20 19:31 UTC, christian-rauch commented
The message about the reset is printed as info, not as warning. From my point of view, clearing the buffer on jumps backward in time is an expected behaviour while the alternative of blocking the synchronisation (by not clearing the buffers) is unexpected.

2018-06-20 20:46 UTC, tfoote commented
info output is fine too. It looks like this is being triggered in the current tests and causing a failure. And related to that we should add a unit test to explicitly test that this is working and won't regress in the future.

2018-06-21 11:11 UTC, christian-rauch commented
The test fails because it not only scrambles the sequence of messages, but also the clock time that is supposed to be continuous: `rospy.rostime._set_rostime(rospy.Time(i+0.05))` where `i` is randomly sampled. Given that we assume that clock time is continuous (but header stamps can be unordered), does this test of synchronising header-less messages sense? I.e. by definition, messages without header do not have an order.

2018-07-09 11:39 UTC, christian-rauch commented
@tfoote Does this look all right to you now?

2018-07-09 18:07 UTC, tfoote approved these changes

2018-11-16 00:52 UTC, dirk-thomas commented
@ros-pull-request-builder retest this please

2018-11-20 23:39 UTC, dirk-thomas commented
@ros-pull-request-builder retest this please

2019-01-31 23:47 UTC, dirk-thomas commented
The C++ equivalent will likely only be part of the next ROS distro (see https://github.com/ros/ros_comm/pull/1518#issuecomment-459550703) I am not sure if you still want to wait with this patch to release them in sync or merge this into Melodic now?

2019-01-31 23:52 UTC, christian-rauch commented
We can merge this now. Then at least people which are using the python interface will benefit from this.

2019-01-31 23:56 UTC, dirk-thomas commented
Sounds good to me. Thanks for the patch.

2019-01-31 23:57 UTC, merged