Fix EINTR handling in XmlRpcDispatch::work
ros/ros_comm pull request #2278
Opened 2022-09-13 11:33 UTC by Hugal31

Only leave XmlRpcDispatchwork if the `poll` error is **not** EINTR.

The EINTR check should probably be at every I/O syscalls, but I think this `poll` call is the only one supposed to block.

Closes #2275

2023-04-09 20:35 UTC, peci1 commented
So what would the function do when EINTR is returned? It would continue to the next part and...? Isn't returning from `work()` the correct thing to do - the next iteration would call `poll()` again, wouldn't it?

2023-04-11 12:11 UTC, Hugal31 commented
> So what would the function do when EINTR is returned? It would continue to the next part and...? Isn't returning from `work()` the correct thing to do - the next iteration would call `poll()` again, wouldn't it?

If EINTR is returned, it would continue, ignore the "process events" block as there is no event, and re-do a poll if there the deadline is not passed.

If we return (the current behavior), the caller would have to handle this case. Right now, `XmlRpcClient::execute` assumes the dispatcher returned because of an error or because the work was done. This caused me issue when debugging or profiling a ROS program (I can't remember exactly, it was quite some time ago).

2023-04-11 13:11 UTC, peci1 requested changes
Right, according to Linux `poll()` documentation, EINTR should only be returned when no events happened, so `revents` should be empty. In that case, the whole "process events" block will probably be a no-op. However, it was actually pretty difficult to figure this out.

I wonder if it weren't easier for code maintainability if there was an explicit `continue` in case of EINTR, with a comment that the `poll()` has to be tried again. The only possible issue I see is that in such case the timeout and clear checks on the end of the loop would be skipped. Another option would be to skip just the "process events" for loop in case poll was interrupted. Or just add a comment explaining what is going to happen.

I also checked the Windows part, but there doesn't seem to be anything similar on Windows. `WSAPoll()` can only be interrupted by a call to a deprecated API function. So it is probably correct that this PR leaves the Windows part as is.

2023-04-11 13:11 UTC, peci1 commented on utilities/xmlrpcpp/src/XmlRpcDispatch.cpp
> +        _inWork = false;
Also, `timeout_ms` has to be recomputed from `_end_time` and `getTime()`. There is probably a larger problem here with `timeout_ms`, as the current implementation calls all `poll()`s with `timeout_ms` regardless of how much time has elapsed from the beginning of the call. Maybe the recomputation of `timeout_ms` should be moved right before the `poll()` call.

2023-04-14 12:09 UTC, Hugal31 commented
I agree that a `continue` would be more readable, but we can't skip the deadline check. Maybe we can add a comment about how the following block will be ignored, or change the loop to check for the deadline at the beginning (maybe using a do while).

2023-04-14 12:39 UTC, peci1 commented
> Maybe we can add a comment

That should be sufficient.

2023-04-18 14:01 UTC, peci1 approved these changes
Thanks for the update!

LGTM.

2024-09-04 21:22 UTC, sloretz approved these changes
Thank you for the PR!

2024-09-04 21:22 UTC, merged