rosgraph: update code from Python 3.11
ros/ros_comm pull request #2297
Opened 2022-11-13 16:47 UTC by jspricke

2023-01-27 14:49 UTC, mjcarroll commented
This one likely needs another pass with test failures.

2023-05-10 10:32 UTC, jspricke commented
I've updated the roslogging patch. This version works for me with Ubuntu 20.04 (ROS Noetic) as well as Debian testing (Python 3.11)

2024-02-26 17:46 UTC, mikepurvis commented
We were having runtime issues with Python 3.11 in our NixOS 23.11 build. I've patched this change on and it seems to be working better. Will report back any new issues we find.

2025-04-25 19:05 UTC, sloretz commented
It looks like the PR job is failing on this one. Mind looking into it?

2025-04-28 08:53 UTC, v4hn commented
The only error is [this one](https://build.ros.org/job/Npr__ros_comm__ubuntu_focal_amd64/643/testReport/test/test_roslogging/test_rosconsole__logging_format/):

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/ws/src/ros_comm/tools/rosgraph/test/test_roslogging.py", line 127, in test_rosconsole__logging_format
    assert_regexp_matches(lout.getvalue().splitlines()[i], log_out)
  File "/usr/lib/python3.8/unittest/case.py", line 1410, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.8/unittest/case.py", line 1388, in assertRegex
    raise self.failureException(msg)
AssertionError: Regex didn't match: 'INFO on module [0-9]*\\.[0-9]* [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{6} [0-9]* rosout /tmp/ws/src/ros_comm/tools/rosgraph/test/test_roslogging\\.py [0-9]* <module> (/unnamed|<unknown_node_name>) [0-9]*\\.[0-9]* [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{6}' not found in 'INFO on module 1728996043.023153 2024-10-15 04:40:43.023163 139950167390016 rosout /usr/bin/nosetests3 11 <module> /unnamed 1728996043.023189 2024-10-15 04:40:43.023192'
```

Likely due to https://github.com/ros/ros_comm/pull/2297/commits/88b9c7f9b8b658478575dafe9adf576dd74e4f7e .

2025-04-28 12:54 UTC, jspricke commented
Not sure anymore how I verified the version in 2023 but I was able to reproduce the test failure and the new version should fix it.

2025-05-05 17:25 UTC, sloretz requested changes, later dismissed

2025-05-05 17:25 UTC, sloretz commented on utilities/xmlrpcpp/test/CMakeLists.txt
> -
Why did you remove this test?

2025-05-05 17:25 UTC, sloretz commented on utilities/xmlrpcpp/src/XmlRpcServer.cpp
> -#endif
Please don't remove this code. It seems to be part of making this work on Windows.

2025-05-05 17:25 UTC, sloretz commented on utilities/roswtf/test/check_roswtf_command_line_online.py.orig
> +#!/usr/bin/env python
I think this file `...py.orig` might have been accidentally committed. Please remove it.

2025-05-05 17:25 UTC, sloretz commented on tools/rosgraph/src/rosgraph/roslogging.py
> +                    break
Why is this change necessary? Where does `_base_logger` come from?

2025-05-06 04:07 UTC, jspricke commented on utilities/xmlrpcpp/test/CMakeLists.txt
> -
See the commit log of: https://github.com/ros/ros_comm/pull/2297/commits/600fedf1a4eb75752baab497d76c6b0642ec6068

This no longer works on Linux.

2025-05-06 04:09 UTC, jspricke commented on utilities/xmlrpcpp/src/XmlRpcServer.cpp
> -#endif
It was specific to Linux, or rather not Windows (`!defined`) and no longer works on Linux. (Same commit as above).

2025-05-06 04:32 UTC, jspricke commented on utilities/roswtf/test/check_roswtf_command_line_online.py.orig
> +#!/usr/bin/env python
done, thx.

2025-05-06 04:34 UTC, jspricke commented on tools/rosgraph/src/rosgraph/roslogging.py
> +                    break
It is the function name from here: https://github.com/ros/ros_comm/blob/noetic-devel/clients/rospy/src/rospy/core.py#L158 also already used here: https://github.com/ros/ros_comm/blob/noetic-devel/tools/rosgraph/src/rosgraph/roslogging.py#L74

2025-05-09 17:51 UTC, sloretz commented on utilities/xmlrpcpp/src/XmlRpcServer.cpp
> -#endif
Ah oops, I missed that `!`.

2025-05-10 09:00 UTC, jspricke commented
closing due to #2388

2025-05-10 09:00 UTC, closed without merging